import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/app_colors.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final textColor = isDark ? AppColors.darkTextPrimary : AppColors.textPrimary;

    return Scaffold(
      appBar: AppBar(
        leading: const BackButton(),
        title: Text(
          'Privacy Policy',
          style: GoogleFonts.poppins(fontWeight: FontWeight.bold),
        ),
        centerTitle: false,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Last Updated: January 1, 2024',
              style: GoogleFonts.inter(
                fontSize: 13,
                color: AppColors.textSecondary,
              ),
            ),
            const SizedBox(height: 20),
            _Section(
              title: 'ConvertIt: Units & Measures — Privacy Policy',
              content:
                  'This Privacy Policy describes how ConvertIt: Units & Measures ("we", "us", or "our") collects, uses, and shares information about you when you use our mobile application.',
              textColor: textColor,
            ),
            _Section(
              title: '1. Information We Collect',
              content:
                  'ConvertIt does not collect any personal information. The app works fully offline and does not require any account creation, login, or network connection.\n\nAll data generated by the app (conversion history, favorites, settings) is stored locally on your device using Android\'s SharedPreferences and is never transmitted to any server.',
              textColor: textColor,
            ),
            _Section(
              title: '2. Data Storage',
              content:
                  'The following data is stored locally on your device only:\n\n• Conversion history (last 50 conversions)\n• Favorite conversion pairs\n• App settings (decimal places, theme, haptic feedback preferences)\n\nThis data is accessible only to you and the app, and is deleted when you uninstall the app.',
              textColor: textColor,
            ),
            _Section(
              title: '3. Permissions',
              content:
                  'ConvertIt requests no special permissions. The app does not access:\n\n• Internet or network state\n• Camera or microphone\n• Contacts or calendar\n• Location\n• Files or storage (beyond app-specific storage)\n• Any device sensors',
              textColor: textColor,
            ),
            _Section(
              title: '4. Third-Party Services',
              content:
                  'ConvertIt does not integrate with any third-party analytics, advertising, or tracking services. There are no ads, no analytics SDKs, and no telemetry.',
              textColor: textColor,
            ),
            _Section(
              title: '5. Currency Rates',
              content:
                  'The currency conversion rates included in this app are hardcoded reference rates and are not fetched from the internet. They may not reflect current market rates. This feature is intended for reference purposes only.',
              textColor: textColor,
            ),
            _Section(
              title: '6. Children\'s Privacy',
              content:
                  'ConvertIt is safe for users of all ages. We do not knowingly collect any personal information from anyone, including children under 13.',
              textColor: textColor,
            ),
            _Section(
              title: '7. Changes to This Policy',
              content:
                  'If we update this Privacy Policy, we will update the "Last Updated" date at the top of this page. We encourage you to review this policy periodically.',
              textColor: textColor,
            ),
            _Section(
              title: '8. Contact Us',
              content:
                  'If you have any questions about this Privacy Policy, please contact us at:\n\nconvertit.app@gmail.com',
              textColor: textColor,
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final String title;
  final String content;
  final Color textColor;

  const _Section({
    required this.title,
    required this.content,
    required this.textColor,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: GoogleFonts.poppins(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: textColor,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: GoogleFonts.inter(
              fontSize: 14,
              height: 1.6,
              color: textColor.withOpacity(0.8),
            ),
          ),
        ],
      ),
    );
  }
}
